__title__ = "AliceBlue_V2"
__description__ = "The Python client for the AliceBlue_V2 trading API"
__url__ = "https://a3.aliceblueonline.com"
__version__ = "1.0"
__author__ = "HK"
__author_email__ = "harshalvkhodifad@gmail.com"